---
title: "Report"
execute: 
  echo: true      # change to true to show the code
code-fold: false  # change to true to fold the code chunks
---

Our group decided to look at the relationship between median housing income across counties in Texas and educational outcomes. Median income information is available through census data and educational data is made public by individual school reporting methods. At the beginning of our project, we included these educational outcomes: graduation rates, college readiness scores, and attendance rates.  We crafted the following guiding research questions:
- What is the relationship between median household income and educational outcomes in Texas?
- Across all counties, what is the range of median household income?
- What are the trends in educational outcomes in Texas across the counties?

As we began our initial analysis, somethings became clear. First, our median income data is by county. Urban counties that house cities like Austin, Houston, and Dallas have higher median incomes, but also have larger populations which means they have more schools and a larger student body to draw information from. This also means that educational data from larger urban centers is less volatile than potential outcomes from smaller communities. The same number of students could not graduate at a high school in Dallas as a high school in rural Texas, but that is unlikely to greatly impact the Dallas county data. However, the smaller population will be more impacted by the same number. Additionally, we discovered that the way high schools determined college readiness shifted during out ten year timeline from 2010 to 2019, making the data about college readiness hard to accruately visualize on a map.

However, we still felt that visualizing the greater trends between educational outcomes and median income in counties in Texas could be valuable. We discovered some interesting trends. First, the average median income across Texas increases during our ten year timeline. This aligns with national economic trends in the US. We also noticed that there is a relatively steady attendance rate across the state over the ten years, meaning that nothing significant happened and attendance rates never severely dropped. We also see that as a general trend, areas that have on average higher median incomes don't necessarily have higher graduation rates. This is likely because of the higher sample size of student populations in the urban centers that both see higher average incomes and lower graduation rates by county. However, the differences across counties are relatively minimal when it comes to graduation rates according to the maps we made. There is also a relationship between test scores and median income. Generally, counties with higher median incomes also have higher average test scores (that indicate college readiness) which is likely due to increased resources in those areas to help students prepare for national testing. 

We also want to note that we had to remove counties in our visualizations that didn't report educational data for each year that we looked at. That is why there are gaps in the map visualizations. Additionally, educational outcomes have selection bias, so while these are trends we noticed, this data does not determine educational success across the state of Texas at all. Our data also doesn't account for impacts to education like COVID-19 which surely had a great impact on the educational outcomes for students across the state, nationally, and globally. 


