---
title: "Proposal"
---

Project Title: The Correlation between Median Housing Income and Educational Outcomes in Texas

Group name: The Stat Stackers

Group members: Owen Lindstrom, Madeleine Heafey, Rachel Kelly

## Description:

We will be exploring the correlation between median housing income and academic outcomes (such as graduation rates, dropout rates, college readiness, enrollment etc) in Texas by county. We chose to study Texas because it is a large state with a lot of diversity in income, population density, political affiliation, etc and as such could help us understand these outcomes across the county.

## Inspiration:

As students, we all feel strongly that correlations between income and educational outcomes should be explored so we can implement systems that better support all students as they navigate the educational system. Education is not equally accessible and we currently live in a world where neighborhood and living location impacts the quality of education one has access to. This varies state to state, but we wanted to see what correlations we might be able to discern from the public education and census data to look at this issue more closely.

## Rough implementation plan:

- Owen is utilizing data from his honors project on Texas which we will use to craft parts of our data analysis.
- Rachel found census data that we will wrangle as a group to layer with the data Owen has already provided.
- Madeleine is reading the case study and will summarize it for the group
- The three of us (four of us if you count "Ghost") are going to wrangle the data and figure out what we want to explore together during class time.
- The three of us will also create the presentation together during class. 
